# Generated by Django 3.0.6 on 2020-06-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200530_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=200)),
                ('network_url', models.URLField()),
                ('network_logo', models.ImageField(upload_to='sc_app/static/media/socialnetworklogos')),
            ],
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SocialNetwork'),
        ),
    ]
