# Generated by Django 3.0.6 on 2020-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200603_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='network_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='network_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='network_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='social_network',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='social_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='company',
            name='social_profiles',
            field=models.ManyToManyField(to='dashboard.SocialProfile'),
        ),
    ]
