# Generated by Django 3.0.6 on 2020-06-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200603_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['name', 'logo', 'url']},
        ),
    ]
