# Generated by Django 3.0.6 on 2020-06-03 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0007_auto_20200603_0532"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="secondary_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_secondary_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(model_name="company", name="primary_contact",),
        migrations.AddField(
            model_name="company",
            name="primary_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_primary_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
