# Generated by Django 3.0.6 on 2020-06-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_auto_20200603_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tertiary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tertiary_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
