# Generated by Django 3.0.6 on 2020-06-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_company_tertiary_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(name="company", options={},),
    ]
