# Generated by Django 3.0.6 on 2020-06-04 06:23

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_auto_20200604_0619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0, default_currency="GBP", max_digits=12
            ),
        ),
    ]
