# Generated by Django 3.0.7 on 2020-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_auto_20200604_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True, null=True, to="dashboard.Subscription"
            ),
        ),
    ]
