# Generated by Django 3.0.7 on 2020-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200612_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
