# Generated by Django 3.0.7 on 2020-06-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200616_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='company_using',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
    ]
