# Generated by Django 3.0.7 on 2020-06-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_subscription_company_using"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="company_using",),
    ]
