# Generated by Django 3.0.7 on 2020-06-24 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_auto_20200623_0729"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
