# Generated by Django 3.0.7 on 2020-06-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_company_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company", options={"ordering": ["name", "created_at"]},
        ),
    ]
